-- MySQL Script generated by MySQL Workbench
-- Wed May  6 14:37:17 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ifamous_dbms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ifamous_dbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifamous_dbms` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ifamous_dbms` ;

-- -----------------------------------------------------
-- Table `ifamous_dbms`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`users` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` CHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `date_created` DATE NOT NULL,
  `last_date_login` DATE NOT NULL,
  `is_utm_staff` TINYINT NOT NULL DEFAULT 0,
  `affiliation` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`coordinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`coordinator` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`coordinator` (
  `user_id` INT NOT NULL,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `coordinator_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`examiners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`examiners` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`examiners` (
  `industry_background` VARCHAR(255) NOT NULL,
  `examiners_id` INT NOT NULL,
  PRIMARY KEY (`examiners_id`),
  CONSTRAINT `examiners_ibfk_1`
    FOREIGN KEY (`examiners_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`supervisor` (
  `research_expertise` VARCHAR(255) NOT NULL,
  `sv_capacity` INT NOT NULL,
  `current_capacity` INT NOT NULL,
  `supervisor_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`supervisor_id`),
  CONSTRAINT `supervisor_ibfk_1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`students` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`students` (
  `metric_number` VARCHAR(20) NOT NULL,
  `student_id` INT NOT NULL,
  `CGPA` FLOAT NOT NULL,
  `GPA` FLOAT NOT NULL,
  `proof_of_credit_hours` VARCHAR(255) NOT NULL,
  `credit_hours_completed` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_id` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `metric_number` (`metric_number` ASC) VISIBLE,
  CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`fyp_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`fyp_session` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`fyp_session` (
  `fyp_session_id` INT NOT NULL,
  PRIMARY KEY (`fyp_session_id`),
  UNIQUE INDEX `fyp_session_id` (`fyp_session_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`projects` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `github_link` VARCHAR(255) NULL DEFAULT NULL,
  `drive_link` VARCHAR(255) NULL DEFAULT NULL,
  `parent_project_id` INT NULL DEFAULT NULL,
  `supervisor_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `fyp_session_id` INT NOT NULL,
  `project_type` ENUM('Research', 'Development') NOT NULL DEFAULT 'Development',
  PRIMARY KEY (`project_id`),
  INDEX `parent_project_id` (`parent_project_id` ASC) VISIBLE,
  INDEX `supervisor_id` (`supervisor_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `fyp_session_id` (`fyp_session_id` ASC) VISIBLE,
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`parent_project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`),
  CONSTRAINT `projects_ibfk_2`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`supervisor` (`supervisor_id`),
  CONSTRAINT `projects_ibfk_3`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`students` (`student_id`),
  CONSTRAINT `projects_ibfk_4`
    FOREIGN KEY (`fyp_session_id`)
    REFERENCES `ifamous_dbms`.`fyp_session` (`fyp_session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`examine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`examine` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`examine` (
  `examiners_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  INDEX `examiners_id` (`examiners_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `examine_ibfk_1`
    FOREIGN KEY (`examiners_id`)
    REFERENCES `ifamous_dbms`.`examiners` (`examiners_id`),
  CONSTRAINT `examine_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`grading_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`grading_table` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`grading_table` (
  `grading_id` INT NOT NULL AUTO_INCREMENT,
  `grading_data` JSON NOT NULL,
  `total_score` FLOAT NOT NULL,
  `comments` VARCHAR(255) NOT NULL,
  `project_id` INT NOT NULL,
  `grader_id` INT NOT NULL,
  PRIMARY KEY (`grading_id`),
  INDEX `grader_id` (`grader_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `grading_table_ibfk_1`
    FOREIGN KEY (`grader_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`),
  CONSTRAINT `grading_table_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`meeting` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`meeting` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `mom` VARCHAR(255) NULL DEFAULT NULL,
  `meeting_date` DATE NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `meeting_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`meeting_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`meeting_schedule` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`meeting_schedule` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `meeting_json` JSON NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `meeting_schedule_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`projects_submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`projects_submissions` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`projects_submissions` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `submission_title` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `submitted_at` DATE NOT NULL,
  `submission_type` ENUM('proposal', 'administrative', 'presentation', 'progress_report', 'final_deliverable', 'logbook') NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT _utf8mb4'pending',
  `project_id` INT NOT NULL,
  PRIMARY KEY (`submission_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `projects_submissions_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`supervisor_nominations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`supervisor_nominations` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`supervisor_nominations` (
  `nomination_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `supervisor_id` INT NOT NULL,
  `preference_order` INT NOT NULL,
  PRIMARY KEY (`nomination_id`),
  UNIQUE INDEX `student_id` (`student_id` ASC, `supervisor_id` ASC) VISIBLE,
  INDEX `supervisor_id` (`supervisor_id` ASC) VISIBLE,
  CONSTRAINT `supervisor_nominations_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`students` (`student_id`),
  CONSTRAINT `supervisor_nominations_ibfk_2`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`supervisor` (`supervisor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`time_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`time_table` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`time_table` (
  `time_table_id` INT NOT NULL AUTO_INCREMENT,
  `schedule_json` JSON NOT NULL,
  `fyp_session_id` INT NOT NULL,
  PRIMARY KEY (`time_table_id`),
  INDEX `fyp_session_id` (`fyp_session_id` ASC) VISIBLE,
  CONSTRAINT `time_table_ibfk_1`
    FOREIGN KEY (`fyp_session_id`)
    REFERENCES `ifamous_dbms`.`fyp_session` (`fyp_session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
