-- MySQL Script generated by MySQL Workbench
-- Sat May 30 12:37:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ifamous_dbms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ifamous_dbms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifamous_dbms` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ifamous_dbms` ;

-- -----------------------------------------------------
-- Table `ifamous_dbms`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`users` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` CHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `date_created` DATE NOT NULL,
  `last_date_login` DATE NOT NULL,
  `is_utm_staff` TINYINT(1) NULL DEFAULT '0',
  `affiliation` VARCHAR(255) NULL DEFAULT NULL,
  `co_org_name` VARCHAR(255) NULL DEFAULT NULL,
  `expertise` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`coordinator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`coordinator` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`coordinator` (
  `user_id` INT NOT NULL,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `coordinator_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`examiners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`examiners` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`examiners` (
  `industry_background` VARCHAR(255) NOT NULL,
  `examiners_id` INT NOT NULL,
  PRIMARY KEY (`examiners_id`),
  CONSTRAINT `examiners_ibfk_1`
    FOREIGN KEY (`examiners_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`supervisor` (
  `research_expertise` VARCHAR(255) NOT NULL,
  `sv_capacity` INT NOT NULL,
  `current_capacity` INT NOT NULL,
  `supervisor_id` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`supervisor_id`),
  CONSTRAINT `supervisor_ibfk_1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`fyp_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`fyp_session` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`fyp_session` (
  `fyp_session_id` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`fyp_session_id`),
  UNIQUE INDEX `fyp_session_id` (`fyp_session_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`fyp_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`fyp_classes` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`fyp_classes` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `fyp_session_id` INT NOT NULL,
  `section_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `unique_session_class` (`fyp_session_id` ASC, `section_name` ASC) VISIBLE,
  CONSTRAINT `fk_class_session`
    FOREIGN KEY (`fyp_session_id`)
    REFERENCES `ifamous_dbms`.`fyp_session` (`fyp_session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`students` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`students` (
  `metric_number` VARCHAR(20) NOT NULL,
  `class_id` INT NULL DEFAULT NULL,
  `student_id` INT NOT NULL,
  `CGPA` FLOAT NOT NULL,
  `GPA` FLOAT NOT NULL,
  `proof_of_credit_hours` VARCHAR(255) NOT NULL,
  `credit_hours_completed` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `student_id` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `metric_number` (`metric_number` ASC) VISIBLE,
  INDEX `fk_student_class` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `ifamous_dbms`.`fyp_classes` (`class_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `students_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`projects` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`projects` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `github_link` VARCHAR(255) NULL DEFAULT NULL,
  `drive_link` VARCHAR(255) NULL DEFAULT NULL,
  `parent_project_id` INT NULL DEFAULT NULL,
  `supervisor_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `fyp_session_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `parent_project_id` (`parent_project_id` ASC) VISIBLE,
  INDEX `supervisor_id` (`supervisor_id` ASC) VISIBLE,
  INDEX `student_id` (`student_id` ASC) VISIBLE,
  INDEX `fyp_session_id` (`fyp_session_id` ASC) VISIBLE,
  CONSTRAINT `projects_ibfk_1`
    FOREIGN KEY (`parent_project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`),
  CONSTRAINT `projects_ibfk_2`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`supervisor` (`supervisor_id`),
  CONSTRAINT `projects_ibfk_3`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`students` (`student_id`),
  CONSTRAINT `projects_ibfk_4`
    FOREIGN KEY (`fyp_session_id`)
    REFERENCES `ifamous_dbms`.`fyp_session` (`fyp_session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`examine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`examine` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`examine` (
  `examiners_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  INDEX `examiners_id` (`examiners_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `examine_ibfk_1`
    FOREIGN KEY (`examiners_id`)
    REFERENCES `ifamous_dbms`.`examiners` (`examiners_id`),
  CONSTRAINT `examine_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`grading_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`grading_table` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`grading_table` (
  `grading_id` INT NOT NULL AUTO_INCREMENT,
  `grading_data` JSON NOT NULL,
  `total_score` FLOAT NOT NULL,
  `comments` VARCHAR(255) NOT NULL,
  `project_id` INT NOT NULL,
  `grader_id` INT NOT NULL,
  PRIMARY KEY (`grading_id`),
  INDEX `grader_id` (`grader_id` ASC) VISIBLE,
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `grading_table_ibfk_1`
    FOREIGN KEY (`grader_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`),
  CONSTRAINT `grading_table_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`meeting` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`meeting` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `mom` VARCHAR(255) NULL DEFAULT NULL,
  `meeting_date` DATE NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `meeting_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`meeting_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`meeting_schedule` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`meeting_schedule` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `meeting_json` JSON NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `meeting_schedule_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`projects_submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`projects_submissions` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`projects_submissions` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `submission_title` VARCHAR(255) NOT NULL,
  `file_path` VARCHAR(255) NOT NULL,
  `submitted_at` DATE NOT NULL,
  `submission_type` ENUM('proposal', 'administrative', 'presentation', 'progress_report', 'final_deliverable', 'logbook') NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT _utf8mb4'pending',
  `project_id` INT NOT NULL,
  PRIMARY KEY (`submission_id`),
  INDEX `project_id` (`project_id` ASC) VISIBLE,
  CONSTRAINT `projects_submissions_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ifamous_dbms`.`projects` (`project_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`supervisor_nominations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`supervisor_nominations` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`supervisor_nominations` (
  `nomination_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `supervisor_id` INT NOT NULL,
  `preference_order` INT NOT NULL,
  PRIMARY KEY (`nomination_id`),
  UNIQUE INDEX `student_id` (`student_id` ASC, `supervisor_id` ASC) VISIBLE,
  INDEX `supervisor_id` (`supervisor_id` ASC) VISIBLE,
  CONSTRAINT `supervisor_nominations_ibfk_1`
    FOREIGN KEY (`student_id`)
    REFERENCES `ifamous_dbms`.`students` (`student_id`),
  CONSTRAINT `supervisor_nominations_ibfk_2`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `ifamous_dbms`.`supervisor` (`supervisor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ifamous_dbms`.`time_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`time_table` ;

CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`time_table` (
  `time_table_id` INT NOT NULL AUTO_INCREMENT,
  `fyp_session_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `class_id` INT NULL DEFAULT NULL,
  `schedule_json` JSON NOT NULL,
  PRIMARY KEY (`time_table_id`),
  UNIQUE INDEX `unique_user_schedule` (`fyp_session_id` ASC, `user_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_class_schedule` (`fyp_session_id` ASC, `class_id` ASC) VISIBLE,
  INDEX `fk_tt_user` (`user_id` ASC) VISIBLE,
  INDEX `fk_tt_class` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_tt_class`
    FOREIGN KEY (`class_id`)
    REFERENCES `ifamous_dbms`.`fyp_classes` (`class_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tt_session`
    FOREIGN KEY (`fyp_session_id`)
    REFERENCES `ifamous_dbms`.`fyp_session` (`fyp_session_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_tt_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ifamous_dbms`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `ifamous_dbms` ;

-- -----------------------------------------------------
-- Placeholder table for view `ifamous_dbms`.`vw_project_scheduling_roster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifamous_dbms`.`vw_project_scheduling_roster` (`project_id` INT, `fyp_session_id` INT, `project_title` INT, `student_details` INT, `supervisor_details` INT, `examiners_json` INT);

-- -----------------------------------------------------
-- procedure sp_CreateCalendarSchedule
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_CreateCalendarSchedule`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_CreateCalendarSchedule`(
    IN p_fyp_session_id INT,
    IN p_is_class TINYINT(1),
    IN p_owner_identifier VARCHAR(255),
    IN p_schedule_json JSON
)
BEGIN
    DECLARE v_session_exists INT DEFAULT 0;

    -- 1. Check if the session exists in the fyp_session table
    SELECT 1 INTO v_session_exists 
    FROM fyp_session 
    WHERE fyp_session_id = p_fyp_session_id LIMIT 1;

    -- 2. If it does not exist, throw a custom error immediately
    IF v_session_exists = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Validation Error: The specified FYP Session does not exist.';
    ELSE
        -- 3. If it does exist, proceed with the insert
        INSERT INTO time_table (
            fyp_session_id, 
            is_class, 
            owner_identifier, 
            schedule_json
        ) 
        VALUES (
            p_fyp_session_id, 
            p_is_class, 
            p_owner_identifier, 
            p_schedule_json
        );
        
        -- Return the newly generated ID back to your backend
        SELECT LAST_INSERT_ID() AS new_time_table_id;
    END IF;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_DeleteCalendarSchedule
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_DeleteCalendarSchedule`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_DeleteCalendarSchedule`(
    IN p_time_table_id INT
)
BEGIN
    -- Deletes the specific schedule record
    DELETE FROM time_table 
    WHERE time_table_id = p_time_table_id;
    
    -- Return the number of affected rows to confirm success to the backend
    SELECT ROW_COUNT() AS affected_rows;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_GetSessionCalendarData
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_GetSessionCalendarData`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_GetSessionCalendarData`(IN p_session_id INT)
BEGIN
    -- Result Set 1: Verify the Session Exists
    SELECT fyp_session_id 
    FROM fyp_session 
    WHERE fyp_session_id = p_session_id;
    -- Result Set 2: Get all Timetables (Sections & Staff) for this session
    SELECT 
        time_table_id,
        is_class,
        owner_identifier,
        schedule_json
    FROM time_table 
    WHERE fyp_session_id = p_session_id;
   
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_SetActiveFYPSession
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_SetActiveFYPSession`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_SetActiveFYPSession`(
    IN p_target_session_id INT
)
BEGIN
    -- Updates all rows in the table. 
    -- If the ID matches the target, it becomes 1 (Active). 
    -- If it doesn't match, it becomes 0 (Inactive).
    UPDATE fyp_session 
    SET is_active = IF(fyp_session_id = p_target_session_id, 1, 0);
    
    -- Return the number of rows that were changed so the backend can verify
    SELECT ROW_COUNT() AS affected_rows;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_UpdateCalendarSchedule
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_UpdateCalendarSchedule`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_UpdateCalendarSchedule`(
    IN p_time_table_id INT,
    IN p_owner_identifier VARCHAR(255),
    IN p_schedule_json JSON
)
BEGIN
    -- Updates only the identifier and the JSON payload. 
    -- is_class is intentionally excluded to make it permanent.
    UPDATE time_table 
    SET 
        owner_identifier = p_owner_identifier,
        schedule_json = p_schedule_json
    WHERE 
        time_table_id = p_time_table_id;
        
    -- Return the number of affected rows to confirm success to the backend
    SELECT ROW_COUNT() AS affected_rows;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_delete_session
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_delete_session`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_delete_session`(
	IN session_id INT
)
BEGIN
	DELETE FROM fyp_session WHERE  fyp_session_id = session_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_all_session
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_get_all_session`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_get_all_session`()
BEGIN
	SELECT * FROM fyp_session;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_insert_session
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_insert_session`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_insert_session`(
IN session_number INT)
BEGIN
	INSERT INTO fyp_session (fyp_session_id) VALUES (session_number);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_lookup_user_role
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_lookup_user_role`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_lookup_user_role`(
	IN email_address VARCHAR(255),
	IN user_id INT
)
BEGIN
	SELECT
		-- Check for presence in sub-tables
		IF(s.student_id IS NOT NULL, 1, 0) AS is_student,
		IF(sv.supervisor_id IS NOT NULL, 1, 0) AS is_supervisor,
		IF(e.examiners_id IS NOT NULL, 1, 0) AS is_examiner,
		IF(c.user_id IS NOT NULL, 1, 0) AS is_coordinator
	FROM users u
	LEFT JOIN students s ON u.user_id = s.student_id
	LEFT JOIN supervisor sv ON u.user_id = sv.supervisor_id
	LEFT JOIN examiners e ON u.user_id = e.examiners_id
	LEFT JOIN coordinator c ON u.user_id = c.user_id
	WHERE u.email = email_address AND u.user_id = user_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_select_session
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_select_session`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_select_session`(
	IN session_number int
)
BEGIN
	SELECT fyp_session_id FROM fyp_session WHERE fyp_session_id = session_number;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_signup_normal_user
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_signup_normal_user`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_signup_normal_user`(
    IN p_email CHAR(255),
    IN p_password_hash VARCHAR(255),
    IN p_full_name VARCHAR(255),
    IN p_phone_number VARCHAR(12),
    IN co_org_name VARCHAR(255),
    IN expertise VARCHAR(255),
    IN p_affiliation VARCHAR(255)
)
BEGIN
    DECLARE v_is_utm_staff TINYINT DEFAULT 0;
    
    -- 1. Check if email or phone number already exists
    IF EXISTS (SELECT 1 FROM `ifamous_dbms`.`users` WHERE `email` = p_email) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: Email already registered.';
    ELSEIF EXISTS (SELECT 1 FROM `ifamous_dbms`.`users` WHERE `phone_number` = p_phone_number) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Error: Phone number already registered.';
    ELSE
        -- 2. Automatic Role Identification based on email suffix (UC102 Step 3-5)
        -- If email contains @utm.my, identify as Internal Staff
        IF p_email LIKE '%@utm.my' THEN
            SET v_is_utm_staff = 1;
        END IF;

		START TRANSACTION;
        -- 3. Insert into users table
        INSERT INTO `ifamous_dbms`.`users` (
            `email`, 
            `password_hash`, 
            `full_name`, 
            `phone_number`, 
            `date_created`, 
            `last_date_login`, 
            `is_utm_staff`, 
            `co_org_name`,
            `expertise`,
            `affiliation`
        ) 
        VALUES (
            p_email, 
            p_password_hash, 
            p_full_name, 
            p_phone_number, 
            CURDATE(), 
            CURDATE(), 
            v_is_utm_staff, 
            co_org_name,
            expertise,
            p_affiliation
        );
        COMMIT;
        -- 4. Return the new User ID for the application to use
        SELECT LAST_INSERT_ID() AS new_user_id;
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_update_session
-- -----------------------------------------------------

USE `ifamous_dbms`;
DROP procedure IF EXISTS `ifamous_dbms`.`sp_update_session`;

DELIMITER $$
USE `ifamous_dbms`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_update_session`(
	IN old_session_id INT,
    IN new_session_id INT
)
BEGIN
	UPDATE fyp_session SET fyp_session_id = new_session_id 
    WHERE fyp_session_id = old_session_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `ifamous_dbms`.`vw_project_scheduling_roster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ifamous_dbms`.`vw_project_scheduling_roster`;
DROP VIEW IF EXISTS `ifamous_dbms`.`vw_project_scheduling_roster` ;
USE `ifamous_dbms`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ifamous_dbms`.`vw_project_scheduling_roster` AS select `project`.`project_id` AS `project_id`,`project`.`fyp_session_id` AS `fyp_session_id`,`project`.`title` AS `project_title`,json_object('student_id',`project`.`student_id`,'full_name',`stu_user`.`full_name`,'metric_number',`s`.`metric_number`,'email',`stu_user`.`email`) AS `student_details`,json_object('supervisor_id',`project`.`supervisor_id`,'full_name',`sv_user`.`full_name`,'email',`sv_user`.`email`) AS `supervisor_details`,coalesce((select json_arrayagg(json_object('examiner_id',`ea`.`examiners_id`,'name',`ex_user`.`full_name`,'email',`ex_user`.`email`)) from (`ifamous_dbms`.`examine` `ea` join `ifamous_dbms`.`users` `ex_user` on((`ea`.`examiners_id` = `ex_user`.`user_id`))) where (`ea`.`project_id` = `project`.`project_id`)),json_array()) AS `examiners_json` from (((`ifamous_dbms`.`projects` `project` join `ifamous_dbms`.`students` `s` on((`project`.`student_id` = `s`.`student_id`))) join `ifamous_dbms`.`users` `stu_user` on((`project`.`student_id` = `stu_user`.`user_id`))) join `ifamous_dbms`.`users` `sv_user` on((`project`.`supervisor_id` = `sv_user`.`user_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
